module.exports = [
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 1",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 2",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 3",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 4",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 5",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 6",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
]