module.exports = [
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 1",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 2",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 3",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 4",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 5",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 6",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 7",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 8",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 9",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 10",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 11",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 12",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 13",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 14",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 15",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 16",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 17",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 18",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 19",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
    {
        "Challenge Name": "Pep_JAVA",
        "Description": "Question 20",
        "Problem Statement": "Take as input a number n.",
        "Input Format": "Integer",
        "Constraints": "n <= 10 ^ 9",
        "Output Format": "String",
        "Tags": "Basics",
    },
]